(("space"     . ((user-emacs-directory . "~/.emacs-distros/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.config/spacemacs/")))))
 ("doom"      . ((user-emacs-directory . "~/.emacs-distros/doom/")))
 ("mpa"      . ((user-emacs-directory . "~/.config/mpa/")))
 ("rational"  . ((user-emacs-directory . "~/.emacs-distros/rational/")
                 (env . (("RATIONAL_EMACS_HOME" . "~/.config/rational-emacs/"))))))
