tap "homebrew/cask-fonts"
tap "d12frosted/emacs-plus"

brew "asdf"
brew "cmake"
brew "emacs-plus@28", args: ["with-no-titlebar", "with-native-comp", "with-modern-nuvola-icon"]
brew "gcc"
brew "ispell"
brew "libgccjit"
brew "neovim"
brew "solargraph"
brew "starship"
brew "stow"
brew "svn"
brew "tldr"
brew "tree"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "font-sauce-code-pro-nerd-font"
cask "font-ubuntu-nerd-font"
cask "google-chrome"
cask "brave-browser"
cask "karabiner-elements"
cask "raycast"
cask "rectangle"
cask "spotify"
cask "visual-studio-code"
cask "whatsapp"
