#+TITLE: Matheus' Mac Config
#+AUTHOR: Matheus Abegg
#+DESCRIPTION: The setup for my Mac.
#+STARTUP: showeverything

* Table of Contents: :toc:
- [[#inspiration--useful-links][Inspiration / Useful links]]
- [[#installation][Installation]]
  - [[#command-line-tools-clt-for-xcode][Command Line Tools (CLT) for Xcode]]
  - [[#clone-the-repo-into-the-homedotfiles][Clone the repo into the $HOME/.dotfiles]]
  - [[#homebrew][Homebrew]]
  - [[#use-the-zsh-installed-by-brew-instead-of-the-one-that-ships-with-osx][Use the ZSH installed by Brew instead of the one that ships with OSx]]
  - [[#install-dotfiles-with-stow]["Install" dotfiles with Stow]]
  - [[#emacs][EMACS]]
  - [[#open-apps-to-trigger-macos-security-permissions][Open Apps to trigger macOS security permissions]]

* Inspiration / Useful links

https://github.com/tecosaur/emacs-config

https://github.com/mathiasbynens/dotfiles

https://orgmode.org/manual/Structure-Templates.html

https://github.com/juanibiapina/dotfiles

* Installation

[[https://brew.sh/][Homebrew]] will install most things and [[https://www.gnu.org/software/stow/][GNU Stow]] will configure them.

Most things, some manual steps are still required. hopefully all will become a single script one day :)

** Command Line Tools (CLT) for Xcode
First of all, we need to update our software and install the Command Line Tools (CLT) for Xcode:

#+BEGIN_SRC bash
sudo softwareupdate --all --install --force
xcode-select --install
sudo reboot
#+END_SRC

** Clone the repo into the $HOME/.dotfiles
#+BEGIN_SRC bash
clone --recurse-submodules git@github.com:mpabegg/dotfiles.git $HOME/.dotfiles

cd ~/.dotfiles
git submodule update --init --recursive
#+END_SRC

** Homebrew
Next we can install [[https://brew.sh/][Homebrew]]

#+BEGIN_SRC bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+END_SRC

And finally we can use brew to install most apps.
I like to use ~-v~ to see what's going on.

Look at the [[./Brewfile][Brewfile]] to see what's being installed.

#+begin_src bash
brew bundle -v
#+end_src

Reboot once again for good measure

#+begin_src bash
sudo reboot
#+end_src

** Use the ZSH installed by Brew instead of the one that ships with OSx
We don't want to rely on major MacOS upgrades to get a new ZSH.

#+begin_src bash
which zsh | sudo tee -a /etc/shells
chsh -s `which zsh`
#+end_src

** "Install" dotfiles with Stow
Best thing ever!

#+begin_src bash
cd ~/.dotfiles
stow */

sudo reboot
#+end_src

** EMACS

*** DOOM Sync
Doom needs to install and sync itself before running the first time, native compilation takes long, grab some tea :)

The executable is already on the $PATH

#+begin_src
doom install
doom sync
#+end_src

*** Link Emacs Apps

I never use the terminal to launch Emacs, and since I want to use the server, I used Automator to create this little app that I can link to the /Appliactions folder.

For this to work, emacs must be running as a daemon. Homebrew takes care of that.

#+begin_src bash
   ln -s ~/.dotfiles/EC.app/ /Applications/
   ls -s /usr/local/Cellar/emacs-plus@28/28.1/Emacs.app/ /Applications/
#+end_src

** Open Apps to trigger macOS security permissions
*** Karabiner
*** Rectangle

**Refresh the SSH key for the new machine and add it to GitHub
